version: '3.9'

services:
    dremio:
        image: dremio/dremio-oss
        hostname: dremio
        ports:
            - "9047:9047"   # UI (HTTP)
            - "31010:31010" # ODBC/JDBC clients
            - "2181:2181"   # ZooKeeper
            - "45678:45678" # Inter-node communication
        networks:
          - elastic
          - dremio 
          - postgres

    postgres:
        image: postgres:10.5
        hostname: postgres
        environment: 
          - POSTGRES_USER=admin
          - POSTGRES_PASSWORD=admin
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
        volumes:
          - ./postgres/postgres-data:/var/lib/postgresql/data
          # copy the sql script to create tables
          - ./postgres/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
          # copy the sql script to fill tables
          - ./postgres/sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
        networks:
          - postgres

    es01:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
        hostname: es01
        container_name: es01
        environment:
          - node.name=es01
          - cluster.name=es-docker-cluster
          - cluster.initial_master_nodes=es01
          - bootstrap.memory_lock=true
          - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
          memlock:
            soft: -1
            hard: -1
        volumes:
          - data01:/usr/share/elasticsearch/data
        ports:
          - 9200:9200
        networks:
          - elastic

    kib01:
        image: docker.elastic.co/kibana/kibana:7.12.1
        hostname: kib01
        container_name: kib01
        ports:
          - 5601:5601
        environment:
          ELASTICSEARCH_URL: http://es01:9200
          ELASTICSEARCH_HOSTS: '["http://es01:9200"]'
        networks:
          - elastic

volumes:
  data01:
    driver: local

networks:
  elastic:
    driver: bridge
  postgres:
    driver: bridge
  dremio:
    driver: bridge
