version: '3.9'

services:
    dremio:
        restart: always
        image: dremio/dremio-oss
        hostname: dremio
        ports:
            - "9047:9047"   # UI (HTTP)
            - "31010:31010" # ODBC/JDBC clients
            - "2181:2181"   # ZooKeeper
            - "45678:45678" # Inter-node communication

    postgres:
        image: postgres:10.5
        hostname: postgres
        environment: 
          - POSTGRES_USER=admin
          - POSTGRES_PASSWORD=admin
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
        volumes:
          - ./postgres/postgres-data:/var/lib/postgresql/data
          # copy the sql script to create tables
          - ./postgres/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
          # copy the sql script to fill tables
          - ./postgres/sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql